language: R
cache: packages
before_install:
  - sudo apt-get install tk
r_packages:
  - covr
  - sm
  - zoo

warnings_are_errors: false

after_success:
  - Rscript -e 'library(covr); codecov()'

ignore:
  - LICENSE
  - vignettes/*html
