language: R
cache: packages

matrix:
  include:
    - os: linux
      r: oldrel
    - os: linux
      r: release
    - os: linux
      r: devel
    - os: osx
      r: release

r_packages:
  - covr
  - sm
  - zoo

warnings_are_errors: false

after_success:
  - Rscript -e 'library(covr); codecov()'

ignore:
  - LICENSE
  - vignettes/*html
